[package]
name = "mevdan-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "mevdan"
path = "src/main.rs"

[dependencies]
mevdan-core = { path = "../mevdan-core" }
mevdan-storage = { path = "../mevdan-storage" }

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[dev-dependencies]
tempfile.workspace = true
assert_cmd = "2"
predicates = "3"
